Translating ch10-00 in French.
Jimskapt/rust-book-fr pull request #106
Opened 2019-10-30 11:37 UTC by Jimskapt

2020-12-12 11:29 UTC, Jimskapt reviewed
Apply suggestions from @xavierforestier in #235

2020-12-12 11:29 UTC, Jimskapt commented on FRENCH/listings/ch10-generic-types-traits-and-lifetimes/listing-10-01/src/main.rs
> +    let mut le_plus_gros = liste_de_nombres[0];
```suggestion
    let mut le_plus_grand = liste_de_nombres[0];
```

2020-12-12 11:29 UTC, Jimskapt commented on FRENCH/listings/ch10-generic-types-traits-and-lifetimes/listing-10-01/src/main.rs
> +        if nombre > le_plus_gros {
```suggestion
        if nombre > le_plus_grand {
```

2020-12-12 11:29 UTC, Jimskapt commented on FRENCH/listings/ch10-generic-types-traits-and-lifetimes/listing-10-01/src/main.rs
> +            le_plus_gros = nombre;
```suggestion
            le_plus_grand = nombre;
```

2020-12-12 11:29 UTC, Jimskapt commented on FRENCH/listings/ch10-generic-types-traits-and-lifetimes/listing-10-01/src/main.rs
> +    println!("Le nombre le plus gros est {}", le_plus_gros);
```suggestion
    println!("Le nombre le plus grand est {}", le_plus_grand);
```

2020-12-12 11:29 UTC, Jimskapt commented on FRENCH/listings/ch10-generic-types-traits-and-lifetimes/listing-10-01/src/main.rs
> +    assert_eq!(le_plus_gros, 100);
```suggestion
    assert_eq!(le_plus_grand, 100);
```

2020-12-12 11:29 UTC, Jimskapt commented on FRENCH/src/ch10-00-generics.md
> +Imaginons un petit programme qui trouve le nombre le gros dans une liste, comme
```suggestion
Imaginons un petit programme qui trouve le nombre le grand dans une liste, comme
```

2020-12-12 11:29 UTC, Jimskapt commented on FRENCH/src/ch10-00-generics.md
> +<span class="caption">Encart 10-1 : le code pour trouver le nombre le plus gros
```suggestion
<span class="caption">Encart 10-1 : le code pour trouver le nombre le plus grand
```

2020-12-12 11:29 UTC, Jimskapt commented on FRENCH/src/ch10-00-generics.md
> +`le_plus_gros`. Ensuite, il parcourt tous les nombres dans la liste, et si le
```suggestion
`le_plus_grand`. Ensuite, il parcourt tous les nombres dans la liste, et si le
```

2021-01-09 10:57 UTC, Jimskapt reviewed
Replace `gros` with `grand`.

2021-02-05 01:10 UTC, Lumenol requested changes
Bonjour, merci pour le travail de traduction.

2021-02-09 18:37 UTC, Jimskapt commented
Merci pour votre aide, @Lumenol ! 👍

2021-05-09 14:40 UTC, MartinHeywang commented on FRENCH/src/ch10-00-generics.md
> +lors de la compilation et de l'exécution du code.
```suggestion
Tous les langages de programmation ont des outils pour gérer la duplication des
concepts. En Rust, un de ces outils est la *généricité*. La généricité permet
de remplacer des types concrets ou d'autres propriétés. Lorsque nous écrivons du
code, nous pouvons exprimer le comportement des types génériques ou comment ils
interagissent avec d'autres types génériques sans savoir ce qu'il y aura à leur place
lors de la compilation et de l'exécution du code.
```

2021-05-23 18:46 UTC, merged

2021-05-23 19:23 UTC, Jimskapt commented
Update of ch10-00 in ad8d13b0a6f0ba30f0d3406df5c12613c04521bd