Translating ch10-01 in French
Jimskapt/rust-book-fr pull request #109
Opened 2019-11-04 19:34 UTC by Jimskapt

Closes #107.

2021-05-14 09:24 UTC, MartinHeywang commented on FRENCH/src/ch10-01-syntax.md
> +des génériques dans la signature de la fonction où nous précisons habituellement
```suggestion
des types génériques dans la signature de la fonction où nous précisons
habituellement
```

2021-05-14 13:59 UTC, MartinHeywang requested changes
Proofread ch10-01 !

Ignore my last review, I messed up.
And I used GitHub suggestions this time (as you can see)

2021-05-15 10:19 UTC, Jimskapt commented on FRENCH/src/ch10-01-syntax.md
> +concrets qui sont utilisés au moment de la compilation.
Do you agree with this tiny change ?

```suggestion
Rust accomplit cela en pratiquant la monomorphisation à la compilation du code
qui utilise les génériques. La *monomorphisation* est un processus qui transforme
du code générique en code spécifique en définissant au moment de la compilation les
types concrets utilisés dans le code.
```

2021-05-15 10:22 UTC, Jimskapt commented on FRENCH/src/ch10-01-syntax.md
> +des génériques dans la signature de la fonction où nous précisons habituellement
Awaiting point of view of @joeljpresent about #270 😉

2021-06-19 17:39 UTC, Jimskapt reviewed
Merci ! 👍

2021-06-21 18:11 UTC, joeljpresent approved these changes

2021-06-21 20:55 UTC, merged