fix 20-02, part 1
Jimskapt/rust-book-fr pull request #363
Opened 2022-02-06 23:01 UTC by poum

up to l928...

2022-02-12 12:57 UTC, Jimskapt requested changes

2022-02-12 12:57 UTC, Jimskapt commented on FRENCH/src/ch20-02-multithreaded.md
> +<span class="caption">Encart 20-10 : simulation d'une requête lente
pourtant c'est bien le traitement de la requête par le serveur qui prends du temps, et non pas le temps que la requête prends pour arriver au serveur ?

2022-02-12 12:57 UTC, Jimskapt commented on FRENCH/src/ch20-02-multithreaded.md
> +type `T` est lié à la valeur de retour, et ceci de nous intéresse pas ici.
```suggestion
type `T` est lié à la valeur de retour, et ceci ne nous intéresse pas ici.
```

2022-02-12 12:57 UTC, Jimskapt commented on FRENCH/src/ch20-02-multithreaded.md
> +moyen de faire ceci ; nous devons donc implémenter cela nous-même.
```suggestion
moyen de faire ceci ; nous devons donc implémenter cela nous-même.
```

2022-02-12 12:57 UTC, Jimskapt commented on FRENCH/src/ch20-02-multithreaded.md
> +fera davantage sens pour vous.
```suggestion
vous sera plus pertinent.
```

2022-02-12 13:02 UTC, Jimskapt commented
Bien joué pour le 2e commit sur la même branche, on évite un conflit cette fois ! 😊

_Vous pouvez aussi créer une `draft pull request` au lieu d'une `pull request` classique si vous n'avez pas encore terminé votre travail (cela peut se choisir sur le bouton éponyme lors de la création de la PR sur GitHub) 😉_

Encore merci pour votre travail minutieux ! 😊

2022-02-13 07:34 UTC, poum commented
j essaie de ne pas refaire mes bêtises. bien noté pour le draft je vais regarder ca, merci pour l info. et avec plaisir, faut bien renvoyer l ascenseur :-)
-------- Message d'origine --------De : Thomas Ramirez ***@***.***> Date : 12/02/2022  14:02  (GMT+01:00) À : Jimskapt/rust-book-fr ***@***.***> Cc : poum ***@***.***>, Author ***@***.***> Objet : Re: [Jimskapt/rust-book-fr] fix 20-02, part 1 (PR #363) 

Bien joué pour le 2e commit sur la même branche, on évite un conflit cette fois ! 😊

Vous pouvez aussi créer une draft pull request au lieu d'une pull request classique si vous n'avez pas encore terminé votre travail (cela peut se choisir sur le bouton éponyme lors de la création de la PR sur GitHub) 😉

Encore merci pour votre travail minutieux ! 😊



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you authored the thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/Jimskapt/rust-book-fr/pull/363#issuecomment-1037219793",

"url": "https://github.com/Jimskapt/rust-book-fr/pull/363#issuecomment-1037219793",

"name": "View Pull Request"

},

"description": "View this Pull Request on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

2022-02-13 18:04 UTC, poum commented on FRENCH/src/ch20-02-multithreaded.md
> +fera davantage sens pour vous.
sera plus explicite pour vous.

2022-02-13 18:07 UTC, poum commented on FRENCH/src/ch20-02-multithreaded.md
> +<span class="caption">Encart 20-10 : simulation d'une requête lente
effectivement, ma compréhension: traitement long => requête longue. "requête effectuant un traitement long" ?

2022-02-14 11:52 UTC, Jimskapt commented on FRENCH/src/ch20-02-multithreaded.md
> +<span class="caption">Encart 20-10 : simulation d'une requête lente
```suggestion
<span class="caption">Encart 20-10 : simulation d'une requête provoquant un long traitement
```

2022-02-17 11:33 UTC, Jimskapt approved these changes

2022-02-17 11:33 UTC, merged